site_name: ChromaPad
site_url: https://chromapad.readthedocs.io
site_description: >-
  ChromaPad documentation.

repo_name: jordanruthe/ChromaPad/
repo_url: https://github.com/jordanruthe/ChromaPad/
nav:
    - Home: index.md
    - Setup:
      - Hardware.md
      - Installation.md
      - Configuration.md
      - Quicktips.md
      - Macros: macros.md
      - Android.md
      - Thumbnails.md
    - Troubleshooting.md
    - Panels:
      - Bed Level/Screws: Screws.md
      - Job_status/Printing: Job_status.md
      - Temperature: Temperature.md
      - Z Calibrate: Zcalibrate.md
    - Screenshots: Panels.md
    - Theming.md
    - Translations.md
    - Breaking Changes: Changelog.md

    - Contact.md
theme:
  name: material
  language: en
  features:
    - content.code.annotate
    - content.tooltips
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: slate
      primary: deep purple

plugins:
    - search

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/jordanruthe/ChromaPad/
      - icon: fontawesome/brands/discord
        link: https://discord.klipper3d.org/
      - icon: fontawesome/brands/python
